-- MySQL Script generated by MySQL Workbench
-- Sun 22 Nov 2020 03:07:42 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`username`));


-- -----------------------------------------------------
-- Table `mydb`.`pacient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacient` (
  `ID` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `pohlavi` VARCHAR(45) NOT NULL,
  `datum_narozeni` DATE NOT NULL,
  `diagnozy` VARCHAR(45) NULL DEFAULT 'diagnozy',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diagnoza_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diagnoza_table` (
  `ID` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `diagnoza` VARCHAR(45) NOT NULL,
  `stav` VARCHAR(45) NOT NULL,
  `datum_vytvoreni` DATE NOT NULL,
  `datum_zmeny` DATE NOT NULL,
  `Diagnosticke_vysetrenia` VARCHAR(45) NULL DEFAULT 'Diagnosticke_vysetrenia',
  `pacient_ID` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`, `pacient_ID`),
  INDEX `fk_diagnoza_table_pacient_idx` (`pacient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_diagnoza_table_pacient`
    FOREIGN KEY (`pacient_ID`)
    REFERENCES `mydb`.`pacient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnosticke_vysetrenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnosticke_vysetrenie` (
  `ID` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `datum_vysetreni` DATE NOT NULL,
  `pracovnik` VARCHAR(45) NOT NULL,
  `ukoly` VARCHAR(45) NULL DEFAULT 'ukoly',
  `diagnoza_table_ID` INT(8) UNSIGNED NOT NULL,
  `diagnoza_table_pacient_ID` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`, `diagnoza_table_ID`, `diagnoza_table_pacient_ID`),
  INDEX `fk_Diagnosticke_vysetrenie_diagnoza_table1_idx` (`diagnoza_table_ID` ASC, `diagnoza_table_pacient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnosticke_vysetrenie_diagnoza_table1`
    FOREIGN KEY (`diagnoza_table_ID` , `diagnoza_table_pacient_ID`)
    REFERENCES `mydb`.`diagnoza_table` (`ID` , `pacient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ukol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ukol` (
  `ID` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `subor_grafickeho_tabletu` VARCHAR(45) NULL,
  `datum_vytovoreni` DATE NOT NULL,
  `datum_zmeny` DATE NOT NULL,
  `velkost_suboru` INT UNSIGNED NULL,
  `Diagnosticke_vysetrenie_ID` INT(8) UNSIGNED NOT NULL,
  `Diagnosticke_vysetrenie_diagnoza_table_ID` INT(8) UNSIGNED NOT NULL,
  `Diagnosticke_vysetrenie_diagnoza_table_pacient_ID` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`, `Diagnosticke_vysetrenie_ID`, `Diagnosticke_vysetrenie_diagnoza_table_ID`, `Diagnosticke_vysetrenie_diagnoza_table_pacient_ID`),
  INDEX `fk_ukol_Diagnosticke_vysetrenie1_idx` (`Diagnosticke_vysetrenie_ID` ASC, `Diagnosticke_vysetrenie_diagnoza_table_ID` ASC, `Diagnosticke_vysetrenie_diagnoza_table_pacient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ukol_Diagnosticke_vysetrenie1`
    FOREIGN KEY (`Diagnosticke_vysetrenie_ID` , `Diagnosticke_vysetrenie_diagnoza_table_ID` , `Diagnosticke_vysetrenie_diagnoza_table_pacient_ID`)
    REFERENCES `mydb`.`Diagnosticke_vysetrenie` (`ID` , `diagnoza_table_ID` , `diagnoza_table_pacient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
